project:
  type: website

website:
  title: "Dave Tirtariyadi"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/davetirtariyadi
      - icon: linkedin
        href: https://www.linkedin.com/in/davetirtariyadi/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

