---
title: "Tidy Tuesday (06/13/2023): SAFI survey data"
author: "Dave Tirtariyadi"
date: "2023-06-13"
categories: [tidy tuesday]
draft: true
execute: 
  message: false
  warning: false
  cache: true
---

```{r}
#| label: load-data-pkgs

safi_data <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-06-13/safi_data.csv')

library(tidyverse)
library(skimr)
```

```{r}
#| label: skim-data

skim(safi_data)
```

```{r}
#| label: data-cleaning

# Convert character NULL's into NA
safi_data$affect_conflicts <- replace(
  safi_data$affect_conflicts, 
  safi_data$affect_conflicts == "NULL", NA)

safi_data <- safi_data %>% 
  # Remove instanceID column
  select(-instanceID) %>% 
  mutate(
    # Factorize village column
    village = factor(village),
    # Factorize respondent_wall_type column
    respondent_wall_type = factor(respondent_wall_type),
    # Convert memb_assoc to logical values
    memb_assoc = case_when(
      memb_assoc == "yes" ~ TRUE,
      memb_assoc == "no" ~ FALSE,
      TRUE ~ NA
    ),
    # Factorize affect_conflicts column
    affect_conflicts = factor(affect_conflicts)
  )
head(safi_data)
```

```{r}
#| label: itemize-data

items_df <- safi_data %>% 
  select(key_ID, items_owned) %>% 
  mutate(
    items_owned = gsub("_", " ", items_owned)
  ) %>% 
  separate_rows(items_owned, sep = ";") %>% 
  unnest(items_owned)

items_df$items_owned <- replace(
  items_df$items_owned, 
  items_df$items_owned == "NULL", NA)

months_lack_food_df <- safi_data %>% 
  select(key_ID, months_lack_food) %>% 
  rename(month = months_lack_food) %>% 
  mutate(month = gsub(";", " ", month)) %>% 
  separate_rows(month, sep = " ") %>% 
  unnest(month)

months_lack_food_df$month <- replace(
  months_lack_food_df$month, 
  months_lack_food_df$month == "none", NA)

months_lack_food_df$month <- str_sub(months_lack_food_df$month, start = 1, end = 3)

unique(months_lack_food_df$month)

months_lack_food_df$month = factor(months_lack_food_df$month, levels = month.abb)
```

```{r}
#| label: most-owned-items

items_df %>% 
  drop_na() %>% 
  group_by(items_owned) %>% 
  count() %>% 
  mutate(items_owned = str_to_title(items_owned)) %>% 
  arrange(desc(n)) %>% 
  ggplot(mapping = aes(x = n, y = fct_reorder(items_owned, n))) + 
  geom_col() + 
  labs(
    x = "",
    y = "",
    title = "Most common items in Tanzania and Mozambique households",
    subtitle = "Radio and mobile phone are the top two items found in households"
  ) +
  theme_minimal()
```

```{r}
#| label: most-common-months

months_lack_food_df %>% 
  drop_na() %>% 
  group_by(month) %>% 
  count() %>% 
  ggplot(aes(x=month, y = n)) +
  geom_col() +
  labs(
    y = "",
    x = "",
    title = "Distribution of Months with Lack of Food",
    subtitle = "Most families struggle to feed the household closer to the end of the year"
  ) +
  theme_minimal()
```
